// Generated by LiveScript 1.5.0
(function(){
  'use strict';
  var arraysCache, getByteArray, createChecker, toString$ = {}.toString, replace$ = ''.replace, split$ = ''.split, slice$ = [].slice;
  arraysCache = {};
  getByteArray = function(arg){
    return arraysCache[arg] || (arraysCache[arg] = toString$.call(arg).slice(8, -1) === 'RegExp'
      ? (function(){
        var i$, x$, ref$, len$, results$ = [];
        for (i$ = 0, len$ = (ref$ = (replace$.call(arg.source, /\W/g, '')).match(/../g)).length; i$ < len$; ++i$) {
          x$ = ref$[i$];
          results$.push(parseInt(x$, 16));
        }
        return results$;
      }())
      : (function(){
        var i$, x$, ref$, len$, results$ = [];
        for (i$ = 0, len$ = (ref$ = split$.call(arg, '')).length; i$ < len$; ++i$) {
          x$ = ref$[i$];
          results$.push(x$.charCodeAt());
        }
        return results$;
      }()));
  };
  createChecker = function(buf){
    return function(){
      var args, res$, i$, to$, offset;
      res$ = [];
      for (i$ = 0, to$ = arguments.length; i$ < to$; ++i$) {
        res$.push(arguments[i$]);
      }
      args = res$;
      offset = 0;
      return args.every(function(it){
        var arr, x$, this$ = this;
        if (typeof it === 'number') {
          offset += it;
          return it >= 0;
        }
        arr = ([].concat(it)).map(getByteArray);
        x$ = arr.some(function(it){
          return it.every((function(it){
            return it === buf[offset + arguments[1]];
          }));
        });
        if (x$) {
          offset += arr[0].length;
        }
        return x$;
      });
    };
  };
  module.exports = function(buf){
    var c, oOfficePrefix, msOfficePrefix, mp4Types, indexOf, getMsOfficeOffset, getMatroskaOffset, checkMp3;
    c = createChecker(buf);
    oOfficePrefix = 'application/vnd.oasis.opendocument';
    msOfficePrefix = 'application/vnd.openxmlformats-officedocument';
    mp4Types = ['mp41', 'mp42', 'isom', 'iso2', 'mmp4', 'M4V', 'dash'];
    indexOf = function(_from, length){
      var args, res$, i$, to$, i;
      res$ = [];
      for (i$ = 2, to$ = arguments.length; i$ < to$; ++i$) {
        res$.push(arguments[i$]);
      }
      args = res$;
      for (i$ = _from, to$ = _from + length; i$ < to$; ++i$) {
        i = i$;
        if (c.apply(null, [i].concat(slice$.call(args)))) {
          return i;
        }
      }
    };
    getMsOfficeOffset = function(){
      var ref$, that;
      return (ref$ = (that = indexOf(4, 2000, 'PK', /03 04/)) != null ? (that = indexOf(that + 4, 1000, 'PK', /03 04/)) != null ? that + 30 : void 8 : void 8) != null
        ? ref$
        : -1;
    };
    getMatroskaOffset = function(){
      var ref$, that;
      return (ref$ = (that = indexOf(4, 4096, /42 82/)) != null ? that + 3 : void 8) != null
        ? ref$
        : -1;
    };
    checkMp3 = function(offset){
      return c(offset, 'ID3') || c(offset, /FF/) && buf[offset + 1] & 0xE2 === 0xE2;
    };
    return function(it){
      return (it != null ? {
        ext: it[0],
        mime: it[1]
      } : void 8) || null;
    }((function(){
      switch (false) {
      case !c(/FF D8 FF/):
        return ['jpg', 'image/jpeg'];
      case !c(/89/, 'PNG\r\n', /1A 0A/):
        return ['png', 'image/png'];
      case !c('GIF'):
        return ['gif', 'image/gif'];
      case !c(8, 'WEBP'):
        return ['webp', 'image/webp'];
      case !c('FLIF'):
        return ['flif', 'image/flif'];
      case !c(['II*\0', 'MM\0*']):
        return (function(){
          switch (false) {
          case !c(8, 'CR'):
            return ['cr2', 'image/x-canon-cr2'];
          default:
            return ['tif', 'image/tiff'];
          }
        }());
      case !c('BM'):
        return ['bmp', 'image/bmp'];
      case !c('II', /BC/):
        return ['jxr', 'image/vnd.ms-photo'];
      case !c('8BPS'):
        return ['psd', 'image/vnd.adobe.photoshop'];
      case !c('PK', /03 04/):
        return (function(){
          switch (false) {
          case !c(30, 'mimetypeapplication/epub+zip'):
            return ['epub', 'application/epub+zip'];
          case !c(30, 'META-INF/mozilla.rsa'):
            return ['xpi', 'application/x-xpinstall'];
          case !c(30, "mimetype" + oOfficePrefix + ".text"):
            return ['odt', oOfficePrefix + ".text"];
          case !c(30, "mimetype" + oOfficePrefix + ".spreadsheet"):
            return ['ods', oOfficePrefix + ".spreadsheet"];
          case !c(30, "mimetype" + oOfficePrefix + ".presentation"):
            return ['odp', oOfficePrefix + ".presentation"];
          case !c(30, ['[Content_Types].xml', '_rels/.rels']):
            return (function(offset){
              return (function(){
                switch (false) {
                case !c(offset, 'word/'):
                  return ['docx', msOfficePrefix + ".wordprocessingml.document"];
                case !c(offset, 'ppt/'):
                  return ['pptx', msOfficePrefix + ".presentationml.presentation"];
                case !c(offset, 'xl/'):
                  return ['xlsx', msOfficePrefix + ".spreadsheetml.sheet"];
                }
              }());
            }.call(this, getMsOfficeOffset()));
          default:
            return ['zip', 'application/zip'];
          }
        }.call(this));
      case !c('PK', [/03/, /05/, /07/], [/04/, /06/, /08/]):
        return ['zip', 'application/zip'];
      case !c(257, 'ustar'):
        return ['tar', 'application/x-tar'];
      case !c('Rar!', /1A 07/, [/00/, /01/]):
        return ['rar', 'application/x-rar-compressed'];
      case !c(/1F 8B 08/):
        return ['gz', 'application/gzip'];
      case !c('BZh'):
        return ['bz2', 'application/x-bzip2'];
      case !c('7z', /BC AF 27 1C/):
        return ['7z', 'application/x-7z-compressed'];
      case !c(/78 01/):
        return ['dmg', 'application/x-apple-diskimage'];
      case !(c('3gp5') || c(/00 00 00/, 1, 'ftyp', mp4Types)):
        return ['mp4', 'video/mp4'];
      case !c('MThd'):
        return ['mid', 'audio/midi'];
      case !c(/1A 45 DF A3/):
        return (function(offset){
          return (function(){
            switch (false) {
            case !c(offset, 'matroska'):
              return ['mkv', 'video/x-matroska'];
            case !c(offset, 'webm'):
              return ['webm', 'video/webm'];
            }
          }());
        }.call(this, getMatroskaOffset()));
      case !c(4, ['ftypqt  ', 'free', 'mdat', 'wide']):
        return ['mov', 'video/quicktime'];
      case !c('RIFF', 4, 'AVI'):
        return ['avi', 'video/x-msvideo'];
      case !c(/30 26 B2 75 8E 66 CF 11 A6 D9/):
        return ['wmv', 'video/x-ms-wmv'];
      case !c(/00 00 01/, [/BA/, /B3/]):
        return ['mpg', 'video/mpeg'];
      case !c(/00 00 00 1C/, 'ftyp3gp4'):
        return ['3gp', 'video/3gpp'];
      case !(checkMp3(0) || checkMp3(1)):
        return ['mp3', 'audio/mpeg'];
      case !(c('M4A ') || c(4, 'ftypM4A')):
        return ['m4a', 'audio/m4a'];
      case !c('OggS'):
        return (function(){
          switch (false) {
          case !c(28, 'OpusHead'):
            return ['opus', 'audio/opus'];
          case !c(28, /80/, 'theora'):
            return ['ogv', 'video/ogg'];
          case !c(28, /01/, 'video\0'):
            return ['ogm', 'video/ogg'];
          case !c(28, /7F/, 'FLAC'):
            return ['oga', 'audio/ogg'];
          case !c(28, 'Speex  '):
            return ['spx', 'audio/ogg'];
          case !c(28, /01/, 'vorbis'):
            return ['ogg', 'audio/ogg'];
          default:
            return ['ogx', 'application/ogg'];
          }
        }());
      case !c('fLaC'):
        return ['flac', 'audio/x-flac'];
      case !c('RIFF', 4, 'WAVE'):
        return ['wav', 'audio/x-wav'];
      case !c('#!AMR\n'):
        return ['amr', 'audio/amr'];
      case !c('%PDF'):
        return ['pdf', 'application/pdf'];
      case !c('MZ'):
        return ['exe', 'application/x-msdownload'];
      case !c(['FWS', 'CWS']):
        return ['swf', 'application/x-shockwave-flash'];
      case !c('{\\rtf'):
        return ['rtf', 'application/rtf'];
      case !c('\0asm'):
        return ['wasm', 'application/wasm'];
      case !c('wOFF', [/00 01 00 00/, 'OTTO']):
        return ['woff', 'font/woff'];
      case !c('wOF2', [/00 01 00 00/, 'OTTO']):
        return ['woff2', 'font/woff2'];
      case !c(8, [/00 00 01/, /01 00 02/, /02 00 02/], 23, 'LP'):
        return ['eot', 'application/octet-stream'];
      case !c(/00 01 00 00 00/):
        return ['ttf', 'font/ttf'];
      case !c('OTTO\0'):
        return ['otf', 'font/otf'];
      case !c(/00 00 01 00/):
        return ['ico', 'image/x-icon'];
      case !c('FLV', /01/):
        return ['flv', 'video/x-flv'];
      case !c('%!'):
        return ['ps', 'application/postscript'];
      case !c(/FD/, '7zXZ', /00/):
        return ['xz', 'application/x-xz'];
      case !c('SQLi'):
        return ['sqlite', 'application/x-sqlite3'];
      case !c('NES', /1A/):
        return ['nes', 'application/x-nintendo-nes-rom'];
      case !c('Cr24'):
        return ['crx', 'application/x-google-chrome-extension'];
      case !c(['MSCF', 'ISc(']):
        return ['cab', 'application/vnd.ms-cab-compressed'];
      case !c('!<arch>'):
        return (function(){
          switch (false) {
          case !c(7, '\ndebian-binary'):
            return ['deb', 'application/x-deb'];
          default:
            return ['ar', 'application/x-unix-archive'];
          }
        }());
      case !c(/ED AB EE DB/):
        return ['rpm', 'application/x-rpm'];
      case !c(/1F/, [/A0/, /9D/]):
        return ['Z', 'application/x-compress'];
      case !c('LZIP'):
        return ['lz', 'application/x-lzip'];
      case !c(/D0C F11E 0 A1 B1 1A E1/):
        return ['msi', 'application/x-msi'];
      case !c(/06 0E 2B 34 02 05 01 01 0D 01 02 01 01 02/):
        return ['mxf', 'application/mxf'];
      case !(c(4, 'G') && (c(192, 'G') || c(196, 'G'))):
        return ['mts', 'video/mp2t'];
      case !c('BLENDER'):
        return ['blend', 'application/x-blender'];
      case !c('BPG', /FB/):
        return ['bpg', 'image/bpg'];
      case !c(/00 00 00 0C/, 'jP  \r\n', /87 0A/):
        return (function(){
          switch (false) {
          case !c(20, 'jp2 '):
            return ['jp2', 'image/jp2'];
          case !c(20, 'jpx '):
            return ['jpx', 'image/jpx'];
          case !c(20, 'jpm '):
            return ['jpm', 'image/jpm'];
          case !c(20, 'mjp2'):
            return ['mj2', 'image/mj2'];
          }
        }());
      case !c('FORM\0'):
        return ['aif', 'audio/aiff'];
      case !c('<?xml '):
        return ['xml', 'application/xml'];
      case !c(60, 'BOOKMOBI'):
        return ['mobi', 'application/x-mobipocket-ebook'];
      case !c(4, 'ftyp'):
        return (function(){
          switch (false) {
          case !c(8, 'mif1'):
            return ['heic', 'image/heif'];
          case !c(8, 'msf1'):
            return ['heic', 'image/heif-sequence'];
          case !c(8, ['heic', 'heix']):
            return ['heic', 'image/heic'];
          case !c(8, ['hevc', 'hevx']):
            return ['heic', 'image/heic-sequence'];
          }
        }());
      }
    }.call(this)));
  };
}).call(this);
